{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "KAP VYK API",
    "description" : "Kap bildirimleri Rest tabanlı api servis projesi",
    "version" : "0.0.1-apinizer-337-07a3583"
  },
  "servers" : [ {
    "url" : "https://apigwdev.mkk.com.tr/api/vyk"
  } ],
  "security" : [ {
    "basicAuth" : [ "read", "write" ]
  } ],
  "paths" : {
    "/members" : {
      "get" : {
        "tags" : [ "Şirket Servisleri" ],
        "summary" : "Şirket Listesi Servisi",
        "description" : "KAP üyesi tüm şirketlerin listesini dönen servistir.",
        "operationId" : "getMembers",
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/MemberInfo"
                },
                "example" : {
                  "title" : "string",
                  "stockCode" : "string",
                  "memberType" : "string",
                  "kfifUrl" : "string"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/memberSecurities" : {
      "get" : {
        "tags" : [ "Şirket Servisleri" ],
        "summary" : "Şirket Menkul Kıymet Bilgileri Servisi",
        "description" : "IGS(işlem gören şirket) tipindeki şirketlerin özet bilgileri ve şirkete ait tüm kıymetlerin genel bilgilerini geri dönen servistir.",
        "operationId" : "getMemberSecurities",
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/MemberSecuritiesResponse"
                },
                "example" : {
                  "member" : {
                    "memberType" : "string",
                    "sermayeSistemi" : "string",
                    "kayitliSermayeTavani" : 1.5,
                    "kstSonGecerlilikTarihi" : "string",
                    "sirketUnvan" : "string",
                    "mksMbrId" : "string"
                  },
                  "securities" : [ {
                    "isin" : "string",
                    "isinDesc" : "string",
                    "borsaKodu" : "string",
                    "takasKodu" : "string",
                    "tertipGroup" : "string",
                    "capital" : 1.5,
                    "currentCapital" : 1.5,
                    "groupCode" : "string",
                    "groupCodeDesc" : "string",
                    "borsadaIslemeAcik" : true
                  } ]
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/memberDetail/{id}" : {
      "get" : {
        "tags" : [ "Şirket Servisleri" ],
        "summary" : "Şirket Detay Servisi",
        "description" : "Sorgulanan şirkete ait genel bilgileri dönen servistir.",
        "operationId" : "getMemberById",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "typeIn" : "path",
          "required" : true,
          "explode" : false,
          "schema" : {
            "title" : "id",
            "pattern" : "^\\d{1,5}$",
            "type" : "string"
          },
          "examples" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/CompanyDetailResponse"
                },
                "example" : {
                  "nameTr" : "string",
                  "nameEn" : "string",
                  "key" : "string",
                  "publishDateTime" : "string"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/lastDisclosureIndex" : {
      "get" : {
        "tags" : [ "Bildirim Servisleri" ],
        "summary" : "Yayınlanmış Son Bildirim id Servisi",
        "description" : "Yayınlanan son Bildirime ait Id bilgisini dönen servistir..",
        "operationId" : "getLastDisclosureIndex",
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/LastDisclosureIndexResponse"
                },
                "example" : {
                  "lastDisclosureIndex" : "string"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/funds" : {
      "get" : {
        "tags" : [ "Fon Servisleri" ],
        "summary" : "Fon Listesi Servisi",
        "description" : "Fon listesini dönen servistir.",
        "operationId" : "getFunds",
        "parameters" : [ {
          "name" : "fundState",
          "in" : "query",
          "typeIn" : "query",
          "required" : false,
          "explode" : true,
          "schema" : {
            "title" : "fundState",
            "type" : "array"
          },
          "examples" : { }
        }, {
          "name" : "fundClass",
          "in" : "query",
          "typeIn" : "query",
          "required" : false,
          "explode" : true,
          "schema" : {
            "title" : "fundClass",
            "type" : "array"
          },
          "examples" : { }
        }, {
          "name" : "fundType",
          "in" : "query",
          "typeIn" : "query",
          "required" : false,
          "explode" : true,
          "schema" : {
            "title" : "fundType",
            "type" : "array"
          },
          "examples" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/FundInfo"
                },
                "example" : {
                  "umbMemberOid" : "string",
                  "fundOid" : "string",
                  "fundId" : 1.5,
                  "fundName" : "string",
                  "fundCode" : "string",
                  "fundType" : "string",
                  "fundClass" : "string",
                  "fundExpiry" : "string",
                  "fundState" : "string",
                  "fundMemberOid" : "string",
                  "umbMemberTypes" : "string",
                  "fundMemberTypes" : "string",
                  "kapUrl" : "string",
                  "nonInactiveCount" : 1.5,
                  "fundCompanyId" : "string",
                  "fundCompanyTitle" : "string"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/fundDetail/{id}" : {
      "get" : {
        "tags" : [ "Fon Servisleri" ],
        "summary" : "Fon Detay Servisi",
        "description" : "Sorgulanan fona ait genel bilgileri dönen servistir.",
        "operationId" : "getFundById",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "typeIn" : "path",
          "required" : true,
          "explode" : false,
          "schema" : {
            "title" : "id",
            "pattern" : "^\\d{1,5}$",
            "type" : "string"
          },
          "examples" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/FundDetailResponse"
                },
                "example" : {
                  "nameTr" : "string",
                  "nameEn" : "string",
                  "key" : "string",
                  "publishDateTime" : "string",
                  "codeKey" : "string"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/downloadAttachment/{id}" : {
      "get" : {
        "tags" : [ "Bildirim Servisleri" ],
        "summary" : "Bildirim Ekleri İndirme Servisi",
        "description" : "Bildirim detay(disclosureDetail) servis dönüşünde yer alan “attachmentUrls” alanından gelen url bilgisi ile downloadAttachment servisi çağrılarak bildirim ekleri indirilir.",
        "operationId" : "getPublicDisclosureFile",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "typeIn" : "path",
          "required" : true,
          "explode" : false,
          "schema" : {
            "title" : "id",
            "type" : "string"
          },
          "examples" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "type" : "string",
                  "format" : "binary"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/disclosures" : {
      "get" : {
        "tags" : [ "Bildirim Servisleri" ],
        "summary" : "Bildirim Listesi Servisi",
        "description" : "Request mesajında gönderilen disclosureIndex’den itibaren ilk 50 bildirime ait tip, sınıf, bildirim id ve rapor id bloğunu getiren servistir.",
        "operationId" : "getDisclosuresInfoList",
        "parameters" : [ {
          "name" : "disclosureIndex",
          "in" : "query",
          "typeIn" : "query",
          "description" : "Gönderilen index ten itibaren listeleme yapılacak Bildirim id bilgisi",
          "required" : true,
          "explode" : true,
          "schema" : {
            "title" : "disclosureIndex",
            "pattern" : "^\\d{1,15}$",
            "type" : "string",
            "description" : "Gönderilen index ten itibaren listeleme yapılacak Bildirim id bilgisi"
          },
          "examples" : { }
        }, {
          "name" : "disclosureTypes",
          "in" : "query",
          "typeIn" : "query",
          "description" : "Listede gönderilmesi beklenen Bildirim tipi",
          "required" : false,
          "explode" : true,
          "schema" : {
            "title" : "disclosureTypes",
            "type" : "string",
            "description" : "Listede gönderilmesi beklenen Bildirim tipi",
            "example" : "FR"
          },
          "examples" : { },
          "example" : "FR"
        }, {
          "name" : "disclosureClass",
          "in" : "query",
          "typeIn" : "query",
          "description" : "Listede gönderilmesi beklenen Bildirim sınıfı",
          "required" : false,
          "explode" : true,
          "schema" : {
            "title" : "disclosureClass",
            "type" : "string",
            "description" : "Listede gönderilmesi beklenen Bildirim sınıfı",
            "example" : "ODA"
          },
          "examples" : { },
          "example" : "ODA"
        }, {
          "name" : "companyId",
          "in" : "query",
          "typeIn" : "query",
          "required" : false,
          "explode" : true,
          "schema" : {
            "title" : "companyId",
            "type" : "array"
          },
          "examples" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/DisclosureInfoResponse"
                },
                "example" : {
                  "disclosureIndex" : "string",
                  "disclosureType" : "string",
                  "disclosureClass" : "string",
                  "subReportIds" : [ "string" ],
                  "title" : "string",
                  "companyId" : "string",
                  "fundId" : "string",
                  "fundCode" : "string",
                  "acceptedDataFileTypes" : [ "string" ]
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/disclosureDetail/{disclosureIndex}" : {
      "get" : {
        "tags" : [ "Bildirim Servisleri" ],
        "summary" : "Bildirim Detay Servisi",
        "description" : "Verilen bildirim indeksine ait bildirimin detaylarını getiren servistir. DisclsureIndex bilgisi disclosures servisinde listelenen numaralardan belirlenebilir.",
        "operationId" : "getDisclosureById",
        "parameters" : [ {
          "name" : "disclosureIndex",
          "in" : "path",
          "typeIn" : "path",
          "description" : "Gönderilen indexe ait bildirim detayı sorgulanır",
          "required" : true,
          "explode" : false,
          "schema" : {
            "title" : "disclosureIndex",
            "pattern" : "^\\d{1,15}$",
            "type" : "string",
            "description" : "Gönderilen indexe ait bildirim detayı sorgulanır"
          },
          "examples" : { }
        }, {
          "name" : "fileType",
          "in" : "query",
          "typeIn" : "query",
          "description" : "File Type (html|data)</i>",
          "required" : true,
          "explode" : true,
          "schema" : {
            "title" : "fileType",
            "pattern" : "(html|data)",
            "type" : "string",
            "description" : "File Type (html|data)</i>",
            "example" : "html"
          },
          "examples" : { },
          "example" : "html"
        }, {
          "name" : "subReportList",
          "in" : "query",
          "typeIn" : "query",
          "description" : "Bu alan gönderilmezse bütün alt raporlar alınır. Bu alan gönderilirse sadece belirtilen rapor id’sine ait detay alınır.",
          "required" : false,
          "explode" : true,
          "schema" : {
            "title" : "subReportList",
            "type" : "string",
            "description" : "Bu alan gönderilmezse bütün alt raporlar alınır. Bu alan gönderilirse sadece belirtilen rapor id’sine ait detay alınır."
          },
          "examples" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/DisclosureByIdResponse"
                },
                "example" : {
                  "blockedStatus" : "string",
                  "disclosureIndex" : "string",
                  "senderId" : "string",
                  "senderTitle" : "string",
                  "senderExchCodes" : [ "string" ],
                  "behalfSenderId" : "string",
                  "behalfSenderTitle" : "string",
                  "behalfSenderExchCodes" : [ "string" ],
                  "behalfFundId" : "string",
                  "behalfFundCode" : "string",
                  "behalfFundTitle" : "string",
                  "disclosureReason" : "string",
                  "disclosureDelayStatus" : "string",
                  "relatedDisclosureIndex" : "string",
                  "disclosureType" : "string",
                  "disclosureClass" : "string",
                  "subject" : {
                    "tr" : "string",
                    "en" : "string"
                  },
                  "consolidation" : "string",
                  "year" : "string",
                  "period" : {
                    "tr" : "string",
                    "en" : "string"
                  },
                  "relatedStocks" : [ {
                    "code" : "string"
                  } ],
                  "summary" : {
                    "tr" : "string",
                    "en" : "string"
                  },
                  "time" : "string",
                  "link" : "string",
                  "attachmentUrls" : [ {
                    "url" : "string",
                    "fileName" : "string"
                  } ],
                  "eventType" : "string",
                  "eventId" : "string",
                  "htmlMessages" : [ {
                    "tr" : "string",
                    "en" : "string"
                  } ],
                  "flatData" : [ { } ],
                  "presentation" : [ { } ],
                  "isBlocked" : "string",
                  "isBlockedDescriptionTr" : "string",
                  "isBlockedDescriptionEn" : "string"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/caEventStatus" : {
      "get" : {
        "tags" : [ "Bildirim Servisleri" ],
        "summary" : "Hak Kullanım Süreç Durum Servisi",
        "description" : "Sorgulanan hak kullanım süreçlerine ait durum bilgisinin listelendiği servistir.",
        "operationId" : "getCAEventStatus",
        "parameters" : [ {
          "name" : "processRefId",
          "in" : "query",
          "typeIn" : "query",
          "description" : "Gönderilen süreç id lere ait süreç durumları listelenir.",
          "required" : true,
          "explode" : true,
          "schema" : {
            "title" : "processRefId",
            "type" : "string",
            "description" : "Gönderilen süreç id lere ait süreç durumları listelenir."
          },
          "examples" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/CAProcessStatus"
                },
                "example" : {
                  "refId" : 1.5,
                  "status" : "string",
                  "statusReason" : "string",
                  "completeDate" : "string"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    },
    "/blockedDisclosures" : {
      "get" : {
        "tags" : [ "Bildirim Servisleri" ],
        "summary" : "Bloklanmış Bildirimler Servisi",
        "description" : "Güncel tarihe kadar KAP sisteminde erişime kapatılan bildirimlerin ve bildirim eklerinin listesi dönülür.",
        "operationId" : "getBlockedDisclosures",
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/BlockedBase"
                },
                "example" : "null"
              }
            }
          },
          "400" : {
            "description" : "Bad Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          },
          "500" : {
            "description" : "Server Error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "title" : "",
                  "$ref" : "#/components/schemas/VykErrorResponse"
                },
                "example" : {
                  "code" : "string",
                  "message" : "string"
                }
              }
            }
          }
        },
        "deprecated" : false,
        "security" : [ {
          "basicAuth" : [ "read", "write" ]
        } ]
      },
      "parameters" : [ ]
    }
  },
  "components" : {
    "schemas" : {
      "VykErrorResponse" : {
        "title" : "VykErrorResponse",
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string",
            "properties" : {
              "code" : {
                "title" : "code",
                "type" : "string"
              }
            }
          },
          "message" : {
            "type" : "string",
            "properties" : {
              "message" : {
                "title" : "message",
                "type" : "string"
              }
            }
          }
        }
      },
      "AuthResponse" : {
        "title" : "AuthResponse",
        "type" : "object",
        "properties" : {
          "token" : {
            "type" : "string",
            "properties" : {
              "token" : {
                "title" : "token",
                "type" : "string",
                "description" : "Sistem tarafından üretilen token bilgisi"
              }
            }
          }
        }
      },
      "MemberInfo" : {
        "title" : "MemberInfo",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "properties" : {
              "id" : {
                "title" : "id",
                "type" : "string"
              }
            }
          },
          "title" : {
            "type" : "string",
            "properties" : {
              "title" : {
                "title" : "title",
                "type" : "string"
              }
            }
          },
          "stockCode" : {
            "type" : "string",
            "properties" : {
              "stockCode" : {
                "title" : "stockCode",
                "type" : "string"
              }
            }
          },
          "memberType" : {
            "type" : "string",
            "properties" : {
              "memberType" : {
                "title" : "memberType",
                "type" : "string"
              }
            }
          },
          "kfifUrl" : {
            "type" : "string",
            "properties" : {
              "kfifUrl" : {
                "title" : "kfifUrl",
                "type" : "string"
              }
            }
          }
        }
      },
      "CompanyInfo" : {
        "title" : "CompanyInfo",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "properties" : {
              "id" : {
                "title" : "id",
                "type" : "string"
              }
            }
          },
          "memberType" : {
            "type" : "string",
            "properties" : {
              "memberType" : {
                "title" : "memberType",
                "type" : "string"
              }
            }
          },
          "sermayeSistemi" : {
            "type" : "string",
            "properties" : {
              "sermayeSistemi" : {
                "title" : "sermayeSistemi",
                "type" : "string"
              }
            }
          },
          "kayitliSermayeTavani" : {
            "type" : "number",
            "properties" : {
              "kayitliSermayeTavani" : {
                "title" : "kayitliSermayeTavani",
                "type" : "number"
              }
            }
          },
          "kstSonGecerlilikTarihi" : {
            "type" : "string",
            "properties" : {
              "kstSonGecerlilikTarihi" : {
                "title" : "kstSonGecerlilikTarihi",
                "type" : "string"
              }
            }
          },
          "sirketUnvan" : {
            "type" : "string",
            "properties" : {
              "sirketUnvan" : {
                "title" : "sirketUnvan",
                "type" : "string"
              }
            }
          },
          "mksMbrId" : {
            "type" : "string",
            "properties" : {
              "mksMbrId" : {
                "title" : "mksMbrId",
                "type" : "string"
              }
            }
          }
        }
      },
      "MemberSecuritiesResponse" : {
        "title" : "MemberSecuritiesResponse",
        "type" : "object",
        "properties" : {
          "member" : {
            "$ref" : "#/components/schemas/CompanyInfo"
          },
          "securities" : {
            "type" : "array",
            "properties" : {
              "securities" : {
                "title" : "securities",
                "type" : "array"
              }
            }
          }
        }
      },
      "MemberSecurity" : {
        "title" : "MemberSecurity",
        "type" : "object",
        "properties" : {
          "isin" : {
            "type" : "string",
            "properties" : {
              "isin" : {
                "title" : "isin",
                "type" : "string"
              }
            }
          },
          "isinDesc" : {
            "type" : "string",
            "properties" : {
              "isinDesc" : {
                "title" : "isinDesc",
                "type" : "string"
              }
            }
          },
          "borsaKodu" : {
            "type" : "string",
            "properties" : {
              "borsaKodu" : {
                "title" : "borsaKodu",
                "type" : "string"
              }
            }
          },
          "takasKodu" : {
            "type" : "string",
            "properties" : {
              "takasKodu" : {
                "title" : "takasKodu",
                "type" : "string"
              }
            }
          },
          "tertipGroup" : {
            "type" : "string",
            "properties" : {
              "tertipGroup" : {
                "title" : "tertipGroup",
                "type" : "string"
              }
            }
          },
          "capital" : {
            "type" : "number",
            "properties" : {
              "capital" : {
                "title" : "capital",
                "type" : "number"
              }
            }
          },
          "currentCapital" : {
            "type" : "number",
            "properties" : {
              "currentCapital" : {
                "title" : "currentCapital",
                "type" : "number"
              }
            }
          },
          "groupCode" : {
            "type" : "string",
            "properties" : {
              "groupCode" : {
                "title" : "groupCode",
                "type" : "string"
              }
            }
          },
          "groupCodeDesc" : {
            "type" : "string",
            "properties" : {
              "groupCodeDesc" : {
                "title" : "groupCodeDesc",
                "type" : "string"
              }
            }
          },
          "borsadaIslemeAcik" : {
            "type" : "boolean",
            "properties" : {
              "borsadaIslemeAcik" : {
                "title" : "borsadaIslemeAcik",
                "type" : "boolean"
              }
            }
          }
        }
      },
      "CompanyDetailResponse" : {
        "title" : "CompanyDetailResponse",
        "type" : "object",
        "properties" : {
          "nameTr" : {
            "type" : "string",
            "properties" : {
              "nameTr" : {
                "title" : "nameTr",
                "type" : "string"
              }
            }
          },
          "nameEn" : {
            "type" : "string",
            "properties" : {
              "nameEn" : {
                "title" : "nameEn",
                "type" : "string"
              }
            }
          },
          "key" : {
            "type" : "string",
            "properties" : {
              "key" : {
                "title" : "key",
                "type" : "string"
              }
            }
          },
          "publishDateTime" : {
            "type" : "string",
            "properties" : {
              "publishDateTime" : {
                "title" : "publishDateTime",
                "type" : "string"
              }
            }
          },
          "value" : {
            "type" : "object",
            "properties" : {
              "value" : {
                "title" : "value",
                "type" : "object"
              }
            }
          }
        }
      },
      "LastDisclosureIndexResponse" : {
        "title" : "LastDisclosureIndexResponse",
        "type" : "object",
        "properties" : {
          "lastDisclosureIndex" : {
            "type" : "string",
            "properties" : {
              "lastDisclosureIndex" : {
                "title" : "lastDisclosureIndex",
                "type" : "string"
              }
            }
          }
        }
      },
      "FundInfo" : {
        "title" : "FundInfo",
        "type" : "object",
        "properties" : {
          "umbMemberOid" : {
            "type" : "string",
            "properties" : {
              "umbMemberOid" : {
                "title" : "umbMemberOid",
                "type" : "string"
              }
            }
          },
          "fundOid" : {
            "type" : "string",
            "properties" : {
              "fundOid" : {
                "title" : "fundOid",
                "type" : "string"
              }
            }
          },
          "fundId" : {
            "type" : "number",
            "properties" : {
              "fundId" : {
                "title" : "fundId",
                "type" : "number"
              }
            }
          },
          "fundName" : {
            "type" : "string",
            "properties" : {
              "fundName" : {
                "title" : "fundName",
                "type" : "string"
              }
            }
          },
          "fundCode" : {
            "type" : "string",
            "properties" : {
              "fundCode" : {
                "title" : "fundCode",
                "type" : "string"
              }
            }
          },
          "fundType" : {
            "type" : "string",
            "properties" : {
              "fundType" : {
                "title" : "fundType",
                "type" : "string"
              }
            }
          },
          "fundClass" : {
            "type" : "string",
            "properties" : {
              "fundClass" : {
                "title" : "fundClass",
                "type" : "string"
              }
            }
          },
          "fundExpiry" : {
            "type" : "string",
            "properties" : {
              "fundExpiry" : {
                "title" : "fundExpiry",
                "type" : "string"
              }
            }
          },
          "fundState" : {
            "type" : "string",
            "properties" : {
              "fundState" : {
                "title" : "fundState",
                "type" : "string"
              }
            }
          },
          "fundMemberOid" : {
            "type" : "string",
            "properties" : {
              "fundMemberOid" : {
                "title" : "fundMemberOid",
                "type" : "string"
              }
            }
          },
          "umbMemberTypes" : {
            "type" : "string",
            "properties" : {
              "umbMemberTypes" : {
                "title" : "umbMemberTypes",
                "type" : "string"
              }
            }
          },
          "fundMemberTypes" : {
            "type" : "string",
            "properties" : {
              "fundMemberTypes" : {
                "title" : "fundMemberTypes",
                "type" : "string"
              }
            }
          },
          "kapUrl" : {
            "type" : "string",
            "properties" : {
              "kapUrl" : {
                "title" : "kapUrl",
                "type" : "string"
              }
            }
          },
          "nonInactiveCount" : {
            "type" : "number",
            "properties" : {
              "nonInactiveCount" : {
                "title" : "nonInactiveCount",
                "type" : "number"
              }
            }
          },
          "fundCompanyId" : {
            "type" : "string",
            "properties" : {
              "fundCompanyId" : {
                "title" : "fundCompanyId",
                "type" : "string"
              }
            }
          },
          "fundCompanyTitle" : {
            "type" : "string",
            "properties" : {
              "fundCompanyTitle" : {
                "title" : "fundCompanyTitle",
                "type" : "string"
              }
            }
          }
        }
      },
      "FundDetailResponse" : {
        "title" : "FundDetailResponse",
        "type" : "object",
        "properties" : {
          "nameTr" : {
            "type" : "string",
            "properties" : {
              "nameTr" : {
                "title" : "nameTr",
                "type" : "string"
              }
            }
          },
          "nameEn" : {
            "type" : "string",
            "properties" : {
              "nameEn" : {
                "title" : "nameEn",
                "type" : "string"
              }
            }
          },
          "key" : {
            "type" : "string",
            "properties" : {
              "key" : {
                "title" : "key",
                "type" : "string"
              }
            }
          },
          "publishDateTime" : {
            "type" : "string",
            "properties" : {
              "publishDateTime" : {
                "title" : "publishDateTime",
                "type" : "string"
              }
            }
          },
          "value" : {
            "type" : "object",
            "properties" : {
              "value" : {
                "title" : "value",
                "type" : "object"
              }
            }
          },
          "codeKey" : {
            "type" : "string",
            "properties" : {
              "codeKey" : {
                "title" : "codeKey",
                "type" : "string"
              }
            }
          }
        }
      },
      "DisclosureInfoResponse" : {
        "title" : "DisclosureInfoResponse",
        "type" : "object",
        "properties" : {
          "disclosureIndex" : {
            "type" : "string",
            "properties" : {
              "disclosureIndex" : {
                "title" : "disclosureIndex",
                "type" : "string"
              }
            }
          },
          "disclosureType" : {
            "type" : "string",
            "properties" : {
              "disclosureType" : {
                "title" : "disclosureType",
                "type" : "string"
              }
            }
          },
          "disclosureClass" : {
            "type" : "string",
            "properties" : {
              "disclosureClass" : {
                "title" : "disclosureClass",
                "type" : "string"
              }
            }
          },
          "subReportIds" : {
            "type" : "array",
            "properties" : {
              "subReportIds" : {
                "title" : "subReportIds",
                "type" : "array"
              }
            }
          },
          "title" : {
            "type" : "string",
            "properties" : {
              "title" : {
                "title" : "title",
                "type" : "string"
              }
            }
          },
          "companyId" : {
            "type" : "string",
            "properties" : {
              "companyId" : {
                "title" : "companyId",
                "type" : "string"
              }
            }
          },
          "fundId" : {
            "type" : "string",
            "properties" : {
              "fundId" : {
                "title" : "fundId",
                "type" : "string"
              }
            }
          },
          "fundCode" : {
            "type" : "string",
            "properties" : {
              "fundCode" : {
                "title" : "fundCode",
                "type" : "string"
              }
            }
          },
          "acceptedDataFileTypes" : {
            "type" : "array",
            "properties" : {
              "acceptedDataFileTypes" : {
                "title" : "acceptedDataFileTypes",
                "type" : "array"
              }
            }
          }
        }
      },
      "AttachmentUrls" : {
        "title" : "AttachmentUrls",
        "type" : "object",
        "properties" : {
          "url" : {
            "type" : "string",
            "properties" : {
              "url" : {
                "title" : "url",
                "type" : "string"
              }
            }
          },
          "fileName" : {
            "type" : "string",
            "properties" : {
              "fileName" : {
                "title" : "fileName",
                "type" : "string"
              }
            }
          }
        }
      },
      "DisclosureByIdResponse" : {
        "title" : "DisclosureByIdResponse",
        "type" : "object",
        "properties" : {
          "blockedStatus" : {
            "type" : "string",
            "properties" : {
              "blockedStatus" : {
                "title" : "blockedStatus",
                "type" : "string"
              }
            }
          },
          "disclosureIndex" : {
            "type" : "string",
            "properties" : {
              "disclosureIndex" : {
                "title" : "disclosureIndex",
                "type" : "string"
              }
            }
          },
          "senderId" : {
            "type" : "string",
            "properties" : {
              "senderId" : {
                "title" : "senderId",
                "type" : "string"
              }
            }
          },
          "senderTitle" : {
            "type" : "string",
            "properties" : {
              "senderTitle" : {
                "title" : "senderTitle",
                "type" : "string"
              }
            }
          },
          "senderExchCodes" : {
            "type" : "array",
            "properties" : {
              "senderExchCodes" : {
                "title" : "senderExchCodes",
                "type" : "array"
              }
            }
          },
          "behalfSenderId" : {
            "type" : "string",
            "properties" : {
              "behalfSenderId" : {
                "title" : "behalfSenderId",
                "type" : "string"
              }
            }
          },
          "behalfSenderTitle" : {
            "type" : "string",
            "properties" : {
              "behalfSenderTitle" : {
                "title" : "behalfSenderTitle",
                "type" : "string"
              }
            }
          },
          "behalfSenderExchCodes" : {
            "type" : "array",
            "properties" : {
              "behalfSenderExchCodes" : {
                "title" : "behalfSenderExchCodes",
                "type" : "array"
              }
            }
          },
          "behalfFundId" : {
            "type" : "string",
            "properties" : {
              "behalfFundId" : {
                "title" : "behalfFundId",
                "type" : "string"
              }
            }
          },
          "behalfFundCode" : {
            "type" : "string",
            "properties" : {
              "behalfFundCode" : {
                "title" : "behalfFundCode",
                "type" : "string"
              }
            }
          },
          "behalfFundTitle" : {
            "type" : "string",
            "properties" : {
              "behalfFundTitle" : {
                "title" : "behalfFundTitle",
                "type" : "string"
              }
            }
          },
          "disclosureReason" : {
            "type" : "string",
            "properties" : {
              "disclosureReason" : {
                "title" : "disclosureReason",
                "type" : "string"
              }
            }
          },
          "disclosureDelayStatus" : {
            "type" : "string",
            "properties" : {
              "disclosureDelayStatus" : {
                "title" : "disclosureDelayStatus",
                "type" : "string"
              }
            }
          },
          "relatedDisclosureIndex" : {
            "type" : "string",
            "properties" : {
              "relatedDisclosureIndex" : {
                "title" : "relatedDisclosureIndex",
                "type" : "string"
              }
            }
          },
          "disclosureType" : {
            "type" : "string",
            "properties" : {
              "disclosureType" : {
                "title" : "disclosureType",
                "type" : "string"
              }
            }
          },
          "disclosureClass" : {
            "type" : "string",
            "properties" : {
              "disclosureClass" : {
                "title" : "disclosureClass",
                "type" : "string"
              }
            }
          },
          "subject" : {
            "$ref" : "#/components/schemas/Subject"
          },
          "consolidation" : {
            "type" : "string",
            "properties" : {
              "consolidation" : {
                "title" : "consolidation",
                "type" : "string"
              }
            }
          },
          "year" : {
            "type" : "string",
            "properties" : {
              "year" : {
                "title" : "year",
                "type" : "string"
              }
            }
          },
          "period" : {
            "$ref" : "#/components/schemas/Period"
          },
          "relatedStocks" : {
            "type" : "array",
            "properties" : {
              "relatedStocks" : {
                "title" : "relatedStocks",
                "type" : "array"
              }
            }
          },
          "summary" : {
            "$ref" : "#/components/schemas/Summary"
          },
          "time" : {
            "type" : "string",
            "properties" : {
              "time" : {
                "title" : "time",
                "type" : "string"
              }
            }
          },
          "link" : {
            "type" : "string",
            "properties" : {
              "link" : {
                "title" : "link",
                "type" : "string"
              }
            }
          },
          "attachmentUrls" : {
            "type" : "array",
            "properties" : {
              "attachmentUrls" : {
                "title" : "attachmentUrls",
                "type" : "array"
              }
            }
          },
          "eventType" : {
            "type" : "string",
            "properties" : {
              "eventType" : {
                "title" : "eventType",
                "type" : "string"
              }
            }
          },
          "eventId" : {
            "type" : "string",
            "properties" : {
              "eventId" : {
                "title" : "eventId",
                "type" : "string"
              }
            }
          },
          "htmlMessages" : {
            "type" : "array",
            "properties" : {
              "htmlMessages" : {
                "title" : "htmlMessages",
                "type" : "array"
              }
            }
          },
          "flatData" : {
            "type" : "array",
            "properties" : {
              "flatData" : {
                "title" : "flatData",
                "type" : "array"
              }
            }
          },
          "presentation" : {
            "type" : "array",
            "properties" : {
              "presentation" : {
                "title" : "presentation",
                "type" : "array"
              }
            }
          },
          "isBlocked" : {
            "type" : "string",
            "properties" : {
              "isBlocked" : {
                "title" : "isBlocked",
                "type" : "string"
              }
            }
          },
          "isBlockedDescriptionTr" : {
            "type" : "string",
            "properties" : {
              "isBlockedDescriptionTr" : {
                "title" : "isBlockedDescriptionTr",
                "type" : "string"
              }
            }
          },
          "isBlockedDescriptionEn" : {
            "type" : "string",
            "properties" : {
              "isBlockedDescriptionEn" : {
                "title" : "isBlockedDescriptionEn",
                "type" : "string"
              }
            }
          }
        }
      },
      "FlatData" : {
        "title" : "FlatData",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "properties" : {
              "id" : {
                "title" : "id",
                "type" : "string"
              }
            }
          },
          "content" : {
            "type" : "object",
            "properties" : {
              "content" : {
                "title" : "content",
                "type" : "object"
              }
            }
          }
        }
      },
      "HtmlMessages" : {
        "title" : "HtmlMessages",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "properties" : {
              "id" : {
                "title" : "id",
                "type" : "string"
              }
            }
          },
          "tr" : {
            "type" : "string",
            "properties" : {
              "tr" : {
                "title" : "tr",
                "type" : "string"
              }
            }
          },
          "en" : {
            "type" : "string",
            "properties" : {
              "en" : {
                "title" : "en",
                "type" : "string"
              }
            }
          }
        }
      },
      "Period" : {
        "title" : "Period",
        "type" : "object",
        "properties" : {
          "tr" : {
            "type" : "string",
            "properties" : {
              "tr" : {
                "title" : "tr",
                "type" : "string"
              }
            }
          },
          "en" : {
            "type" : "string",
            "properties" : {
              "en" : {
                "title" : "en",
                "type" : "string"
              }
            }
          }
        }
      },
      "Presentation" : {
        "title" : "Presentation",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "properties" : {
              "id" : {
                "title" : "id",
                "type" : "string"
              }
            }
          },
          "content" : {
            "type" : "object",
            "properties" : {
              "content" : {
                "title" : "content",
                "type" : "object"
              }
            }
          }
        }
      },
      "RelatedStock" : {
        "title" : "RelatedStock",
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string",
            "properties" : {
              "code" : {
                "title" : "code",
                "type" : "string"
              }
            }
          }
        }
      },
      "Subject" : {
        "title" : "Subject",
        "type" : "object",
        "properties" : {
          "tr" : {
            "type" : "string",
            "properties" : {
              "tr" : {
                "title" : "tr",
                "type" : "string"
              }
            }
          },
          "en" : {
            "type" : "string",
            "properties" : {
              "en" : {
                "title" : "en",
                "type" : "string"
              }
            }
          }
        }
      },
      "Summary" : {
        "title" : "Summary",
        "type" : "object",
        "properties" : {
          "tr" : {
            "type" : "string",
            "properties" : {
              "tr" : {
                "title" : "tr",
                "type" : "string"
              }
            }
          },
          "en" : {
            "type" : "string",
            "properties" : {
              "en" : {
                "title" : "en",
                "type" : "string"
              }
            }
          }
        }
      },
      "CAProcessStatus" : {
        "title" : "CAProcessStatus",
        "type" : "object",
        "properties" : {
          "refId" : {
            "type" : "number",
            "properties" : {
              "refId" : {
                "title" : "refId",
                "type" : "number"
              }
            }
          },
          "status" : {
            "type" : "string",
            "properties" : {
              "status" : {
                "title" : "status",
                "type" : "string"
              }
            }
          },
          "statusReason" : {
            "type" : "string",
            "properties" : {
              "statusReason" : {
                "title" : "statusReason",
                "type" : "string"
              }
            }
          },
          "completeDate" : {
            "type" : "string",
            "properties" : {
              "completeDate" : {
                "title" : "completeDate",
                "type" : "string"
              }
            }
          }
        }
      },
      "BlockedBase" : {
        "title" : "BlockedBase",
        "type" : "object"
      }
    },
    "securitySchemes" : {
      "basicAuth" : {
        "type" : "http",
        "scheme" : "basic"
      }
    }
  }
}